Improve cmake install path for extraction tools
vmangos/core pull request #2803
Opened 2024-10-18 18:20 UTC by schell244

## 🍰 Pullrequest
Copy map extraction tools into ${BIN_DIR}/Extractors folder, also copy offmesh.txt and config.json to the same location.
Added a more consistent naming scheme for the tools:
mapextractor -> MapExtractor
MoveMapGen -> MoveMapGenerator
vmap_assembler -> VMapAssembler
vmapextractor -> VMapExtractor 

### How2Test
- Compile with USE_EXTRACTORS = 1
- CMakePredefinedTargets -> INSTALL
- map extraction tools will be copied into Extractors folder

### Todo / Checklist
- [X] None

2024-10-18 18:36 UTC, mserajnik commented
The executable names (`MoveMapGen` and `MoveMapGen.exe`) will have do be adjusted in this script too then: https://github.com/vmangos/core/blob/development/contrib/mmap/mmap_extract.py

2024-10-18 22:22 UTC, 0blu requested changes

2024-10-18 22:22 UTC, 0blu commented on contrib/extractor/CMakeLists.txt
> +  install(FILES ${CMAKE_SOURCE_DIR}/bin/Debug/MapExtractor.pdb DESTINATION ${BIN_DIR}/Extractors CONFIGURATIONS Debug)
`BIN_DIR` is correct (which is the install path) but you have to adjust the source, use `${CMAKE_BINARY_DIR}` for that.

2024-10-18 22:22 UTC, 0blu commented on contrib/mmap/CMakeLists.txt
> +  install(FILES ${CMAKE_SOURCE_DIR}/bin/Debug/MoveMapGenerator.pdb DESTINATION ${BIN_DIR}/Extractors CONFIGURATIONS Debug)
Same as above

2024-10-20 16:28 UTC, 0blu approved these changes
lgtm! I would squash merge it.

2024-10-20 18:27 UTC, mserajnik approved these changes
Since the script needs to be placed in the same directory as the `MoveMapGenerator` executable to work anyway, this seems like a good addition to me so the users don't have to do that manually.

2024-10-21 11:49 UTC, mserajnik commented
Hm, how about also renaming `mmap_extract.py` to something more consistent? Maybe `GenerateMoveMaps.py`; or maybe better `generate_move_maps.py` if we want a different style to visually distinguish the script more from the compiled executables. Not sure what would be preferable here.

2024-10-22 20:50 UTC, merged